---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Parallel Data Compression"
keywords:    "project, carnegie mellon, computer science, parallel, compression, github"
description: "Project website for Jeremy Ong and Cyrus Daruwala's final 15-418 project."
source_link: "https://github.com/jearmoo/parallel-data-compression"
favicon:     "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  white:     '#f8f8f8'
  black:     '#111111'

  snow:      '#FBFAF8'
  palm-leaf: '#698F3F'
  tuscan:    '#804E49'
  rich-black: '#0A122A'
  almond:    '#E7DECD'

  purple:    '#c869bf'

kramdown:
  auto_ids:  false

